version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: ghcujnsh
      POSTGRES_PASSWORD: bIWDRtPjzzhD5NY-c7NBat3hbljy-dwD

